name: CI

run-name: CI - ${{ github.event_name == 'pull_request' && github.event.pull_request.title || github.event_name == 'push' && github.event.head_commit.message || github.ref_name }} ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version != '' && format('(v{0})', github.event.inputs.version) || '' }}

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        default: "None"
        required: false

permissions:
  contents: read

env:
  CI: "true"

jobs:
  # Continuous Integration (CI) pipeline
  ci:
    if: ${{ vars.CONTINUOUS_INTEGRATION == 'true' }}
    permissions:
      contents: read
    env:
      RELEASE_MODE: "false"
      VERSION: ${{ github.run_id }}
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        platforms: [linux/amd64, linux/arm64]
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Install dependencies
        shell: bash
        run: uvx uvtask ci-install

      - name: security-analysis-licenses
        shell: bash
        run: uvx uvtask security-analysis:licenses

      - name: security-analysis-vulnerabilities-code
        shell: bash
        run: uvx uvtask security-analysis:vulnerabilities:code

      - name: security-analysis-vulnerabilities-pkgs
        shell: bash
        run: uvx uvtask security-analysis:vulnerabilities:pkgs

      - name: static-analysis-linter
        shell: bash
        run: uvx uvtask static-analysis:linter

      - name: static-analysis-types
        shell: bash
        run: uvx uvtask static-analysis:types

      - name: complexity-visibility
        shell: bash
        run: uvx uvtask complexity:visibility

      - name: complexity-enforcement
        shell: bash
        run: uvx uvtask complexity:enforcement

      - name: unit-tests
        shell: bash
        run: uvx uvtask unit-tests

      - name: integration-tests
        shell: bash
        run: uvx uvtask integration-tests

      - name: Clean
        if: always()
        shell: bash
        run: uvx uvtask clean
